#!/usr/bin/env python3
"""Generate machine-readable design tokens from the single source of truth."""
import json, os
from _palette import COLORS, contrast

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

# Semantic roles per theme, as references into COLORS. Declared once; the CSS
# emits it three times (media query + both data-theme overrides).
SEMANTIC = {
    "light": {"bg": "paper", "fg": "ink",    "accent": "green", "border": "border-sand"},
    "dark":  {"bg": "ink",   "fg": "paper",  "accent": "mint",  "border": "border-slate"},
}

TYPOGRAPHY = {
    "family": {
        "sans": "Inter, system-ui, -apple-system, 'Segoe UI', sans-serif",
        "mono": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    },
    "weight": {"regular": 400, "medium": 500},
    "note": "Wordmark: Inter Medium (500), lowercase. Never use weights above 500.",
}

GEOMETRY = {
    "seal": {
        "viewbox": 240, "center": [120, 120], "radius": 98,
        "ring_stroke": 9, "ring_dasharray": [16, 9],
        "check_path": "M 72 122 L 109 166 L 172 81", "check_stroke": 16,
    },
    "clearspace": "3 × ring stroke width on all sides",
    "min_size_px": {"icon": 16, "lockup_height": 24},
}

# Hairlines carry structure, so WCAG 1.4.11 asks 3:1 of them — and the guide
# says so in prose. Enforce it here instead: a rule a generator checks cannot
# drift out of one theme while the other keeps it. Both past defects fail this
# floor — the dark hairline that resolved to its own background (1.00:1), and
# the light one left at 1.33:1 when the dark side was fixed. Print every
# measurement on each run: the brand argues numbers, so the palette states its
# own.
HAIRLINE_MIN = 3.0

def check_semantics():
    for theme, roles in SEMANTIC.items():
        for role, name in roles.items():
            if name not in COLORS:
                raise SystemExit(f"{theme}/{role}: unknown colour '{name}'")
        ratio = contrast(roles["border"], roles["bg"])
        print(f"  {theme:5s} hairline {roles['border']:12s} on {roles['bg']:5s} = {ratio:.2f}:1")
        if ratio < HAIRLINE_MIN:
            raise SystemExit(
                f"{theme}: hairline '{roles['border']}' on '{roles['bg']}' is "
                f"{ratio:.2f}:1, below the {HAIRLINE_MIN:g}:1 floor — a divider "
                f"that cannot be seen is a divider that is not there"
            )

def semantic_block(theme, indent):
    pad = " " * indent
    return [f"{pad}/* semantic ({theme}) */"] + [
        f"{pad}--probavi-{role}: var(--probavi-{name});"
        for role, name in SEMANTIC[theme].items()
    ]

def main():
    tokens = {
        "$schema": "https://probavi.dev/schemas/brand-tokens-1.json",
        "version": 1,
        "color": COLORS,
        "typography": TYPOGRAPHY,
        "geometry": GEOMETRY,
    }
    with open(f"{ROOT}/tokens/tokens.json", "w") as f:
        json.dump(tokens, f, indent=2)
        f.write("\n")

    lines = [
        "/* Probavi design tokens — GENERATED by tools/gen_tokens.py. Do not edit. */",
        ":root {",
    ]
    for name, c in COLORS.items():
        lines.append(f"  --probavi-{name}: {c['hex']};")
    lines += [
        f"  --probavi-font-sans: {TYPOGRAPHY['family']['sans']};",
        f"  --probavi-font-mono: {TYPOGRAPHY['family']['mono']};",
        "",
    ]
    lines += semantic_block("light", 2)
    lines += [
        "}",
        "",
        "/* Automatic: follow the OS preference when the page states no preference. */",
        "@media (prefers-color-scheme: dark) {",
        "  :root {",
    ]
    lines += semantic_block("dark", 4)
    lines += [
        "  }",
        "}",
        "",
        "/* Manual: an explicit theme on <html> wins over the OS preference, in both",
        "   directions (Starlight and friends set data-theme from their toggle).",
        "   Placed after the media query so source order says so too, not only",
        "   selector specificity. */",
        ':root[data-theme="dark"] {',
    ]
    lines += semantic_block("dark", 2)
    lines += [
        "}",
        "",
        ':root[data-theme="light"] {',
    ]
    lines += semantic_block("light", 2)
    lines += ["}"]

    with open(f"{ROOT}/tokens/tokens.css", "w") as f:
        f.write("\n".join(lines) + "\n")

    print("Generated tokens/tokens.json and tokens/tokens.css")

if __name__ == "__main__":
    os.makedirs(f"{ROOT}/tokens", exist_ok=True)
    check_semantics()
    main()
