#!/usr/bin/env python3
"""Generate machine-readable design tokens from the single source of truth."""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

COLORS = {
    "ink":         {"hex": "#1E2A4A", "rgb": [30, 42, 74],    "role": "Primary. Text, ring, dark surfaces."},
    "green":       {"hex": "#0E9F6E", "rgb": [14, 159, 110],  "role": "The check, success, 'proven'. Accent only."},
    "mint":        {"hex": "#4ADE9D", "rgb": [74, 222, 157],  "role": "The check on dark surfaces; success text in dark UI."},
    "paper":       {"hex": "#F5F0E8", "rgb": [245, 240, 232], "role": "Light background; light elements on Ink."},
    "border-sand": {"hex": "#D8D2C4", "rgb": [216, 210, 196], "role": "Hairlines on Paper."},
}

TYPOGRAPHY = {
    "family": {
        "sans": "Inter, system-ui, -apple-system, 'Segoe UI', sans-serif",
        "mono": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    },
    "weight": {"regular": 400, "medium": 500},
    "note": "Wordmark: Inter Medium (500), lowercase. Never use weights above 500.",
}

GEOMETRY = {
    "seal": {
        "viewbox": 240, "center": [120, 120], "radius": 98,
        "ring_stroke": 9, "ring_dasharray": [16, 9],
        "check_path": "M 72 122 L 109 166 L 172 81", "check_stroke": 16,
    },
    "clearspace": "3 × ring stroke width on all sides",
    "min_size_px": {"icon": 16, "lockup_height": 24},
}

def main():
    tokens = {
        "$schema": "https://probavi.dev/schemas/brand-tokens-1.json",
        "version": 1,
        "color": COLORS,
        "typography": TYPOGRAPHY,
        "geometry": GEOMETRY,
    }
    with open(f"{ROOT}/tokens/tokens.json", "w") as f:
        json.dump(tokens, f, indent=2)
        f.write("\n")

    lines = [
        "/* Probavi design tokens — GENERATED by tools/gen_tokens.py. Do not edit. */",
        ":root {",
    ]
    for name, c in COLORS.items():
        lines.append(f"  --probavi-{name}: {c['hex']};")
    lines += [
        f"  --probavi-font-sans: {TYPOGRAPHY['family']['sans']};",
        f"  --probavi-font-mono: {TYPOGRAPHY['family']['mono']};",
        "",
        "  /* semantic (light) */",
        "  --probavi-bg: var(--probavi-paper);",
        "  --probavi-fg: var(--probavi-ink);",
        "  --probavi-accent: var(--probavi-green);",
        "  --probavi-border: var(--probavi-border-sand);",
        "}",
        "",
        "@media (prefers-color-scheme: dark) {",
        "  :root {",
        "    --probavi-bg: var(--probavi-ink);",
        "    --probavi-fg: var(--probavi-paper);",
        "    --probavi-accent: var(--probavi-mint);",
        "    --probavi-border: var(--probavi-ink);",
        "  }",
        "}",
    ]
    with open(f"{ROOT}/tokens/tokens.css", "w") as f:
        f.write("\n".join(lines) + "\n")

    print("Generated tokens/tokens.json and tokens/tokens.css")

if __name__ == "__main__":
    os.makedirs(f"{ROOT}/tokens", exist_ok=True)
    main()
